# Generated by Django 5.1.3 on 2024-11-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategorymodel',
            name='tasks',
        ),
    ]
