# Generated by Django 5.1.3 on 2024-11-28 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
