# Generated by Django 5.1.3 on 2024-11-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
