# Generated by Django 5.1.3 on 2024-12-02 05:24

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing',
            name='balance_after_borrowing',
            field=models.DecimalField(max_digits=10, decimal_places=2, default=decimal.Decimal('0.00')),
            preserve_default=False,
        ),
    ]
