# Generated by Django 5.1.3 on 2024-12-02 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_borrowing_balance_after_borrowing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Borrowing',
        ),
    ]
