# Generated by Django 5.1.3 on 2024-11-25 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_titile', models.CharField(max_length=50)),
                ('task_description', models.TextField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateField(default=datetime.datetime(2024, 11, 25, 2, 45, 19, 765847))),
            ],
        ),
    ]
