# Generated by Django 5.1.3 on 2024-11-25 02:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_taskcategorymodel_tasks'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(related_name='tasks', to='categories.taskcategorymodel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='task_assign_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 25, 2, 47, 7, 523761)),
        ),
    ]
