# Generated by Django 5.1.3 on 2024-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianmodel',
            name='instrument_type',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano'), ('drums', 'Drums'), ('violin', 'Violin'), ('flute', 'Flute'), ('saxophone', 'Saxophone'), ('trumpet', 'Trumpet')], max_length=200),
        ),
    ]
